### ISSUE TITLE
I have some questions about rabbitmq

### ISSUE THREAD

**Issue by ffff-0214** [microservices-practical/microservices-v8#1]
Hello, I am doing a spring boot project after I learned from your code.
For example, in order to loading balancing better, I launched two instances of gamification.
And the problem is that what happens when receiving a message from rabbitmq.
Will both instances execute the same process？
Since two instances have the same queue, they may cause the same operation to the database twice.
So how to solve such a problem?
Thanks!

**Comment by mechero** [comment]
Hi! Sorry, it took me a while to respond. 

If both instances consume **from the same queue**, they'll get a message each and therefore you'll be implementing a worker pattern, which is what you want to achieve if I understood you correctly. You should avoid creating different queues for those instances since then you'll get the problem you mention.

I hope this helps! Kind regards,
Moisés
